### ISSUE TITLE
Feature request: change icon delimiter

### ISSUE THREAD

**Issue by keysmashes** [cboddy/i3-workspace-names-daemon#1]
I'd really like a feature to change the delimiter used for multiple icons, currently hardcoded to `|`:

https://github.com/cboddy/i3-workspace-names-daemon/blob/45cc09d3fbc961477d87577da5319b2f4ff71b9e/i3_workspace_names_daemon.py#L50

**Comment by kensand** [comment]
Agreed, I'll make a quick pull request for this.

**Comment by kensand** [comment]
pull request is here if you want to patch your own version #5 its the second commit in the pr (whoops)

**Comment by cboddy** [comment]
Thanks @kensand  @anowlcalledjosh , I've merged it, bump the version  and uploaded a new version to pypi.
