### ISSUE TITLE
doesn't work for workspace 0

### ISSUE THREAD

**Issue by acrisci** [cboddy/i3-workspace-names-daemon#12]
If I have a workspace called "0" and I open urxvt there, I would expect it to rename it to "0: urxvt" but it opens a new workspace called "urxvt" instead.

**Comment by cboddy** [comment]
Hi, that's interesting. 

Can you check the README section about the i3-config? I thought the i3-workspace numbers started at 1 (not 0) - can you just use that instead?

**Comment by acrisci** [comment]
Workspace numbers start at 0 and I'd like to keep my setup that way because that's what I'm used to.

**Comment by kensand** [comment]
I'm pretty sure workspace numbers do not start at 0 in i3, they start at 1 and go up from there. Workspaces with the number 0 are workspaces that are (supposed to be) named and not numbered. I know it's not quite defined, but it notes that by default the numbering starts at 1 here: https://i3wm.org/docs/4.0/userguide.html#workspace_screen . I will see if I can find the source of that info later on.

**Comment by cboddy** [comment]
> Workspace numbers start at 0 

I can't find anything particularly clear about this in the i3 docs but the auto-generated configs have workspaces that start at 1, rather than 0. If you can link to something to the contrary please do :), otherwise I don't think there is anything to do.
