### ISSUE TITLE
i3-regolith folder not supported

### ISSUE THREAD

**Issue by JonasLoos** [cboddy/i3-workspace-names-daemon#13]
If one uses the `regolith-desktop` package on Ubuntu, the i3 config files lie in [~/.config/i3-regolith](https://regolith-linux.org/internals.html) while i3-workspace-names-daemon uses `~/.config/i3/` for the icons.

The `i3` folder still works fine. But it would be nice, if only one config-folder is necessary.

Same problem probably occurs on Regolith Linux too.

**Comment by cboddy** [comment]
regolith is (exciting) news to me, I've added support for it in https://github.com/cboddy/i3-workspace-names-daemon/commit/88fd460f4697d4baeaa9250a03d13953bdbbc86d, available in version 0.11.0 on pypi.
