### ISSUE TITLE
Support i3ipc >= 2.0

### ISSUE THREAD

**Issue by steinex** [cboddy/i3-workspace-names-daemon#14]
Hi,

with i3ipc 2.0.1, i3-workspace-names-daemon doesn't work anymore. It starts up but exits after a few seconds without any output.

I didn't dig deep into it, just wanted to let you know. Downgrading to i3ipc 1.7.1 helped. It would be nice if that could be fixed.

Thanks for this great tool.

**Comment by cboddy** [comment]
Thanks for posting this issue -  I didn't know ``i3ipc`` was working towards a new major release. I can reproduce it.

As a quick-fix I've pinned to i3ipc to 1.7.1 and released ``i3-workspace-names-daemon``  ``0.12.0``  to pypi.

I will try to update to  the newer i3ipc but not soon - please feel free to take a look into it too :)

Can you confirm the new release works for you?

**Comment by steinex** [comment]
I can confirm `0.12.0` works for me.

Thanks!
