### ISSUE TITLE
Focus loss in multi monitor setup

### ISSUE THREAD

**Issue by heinrob** [cboddy/i3-workspace-names-daemon#18]
I have a multi monitor setup and every time a window title changes, a workspace on the other monitor is focused.
A title change happens for example in the following examples:

- nemo: change folder
- vscode: begin to edit a file (little dot appears to visualize unsaved changes)
- firefox: opening a new tab
- ...

which is a pretty funny but annoying behavior.

version: `0.13.0`

**Comment by cboddy** [comment]
Thanks for raising, not seen this - will try to reproduce with multi monitor setup.

**Comment by heinrob** [comment]
What are the lines 85 and 86 supposed to do?

https://github.com/cboddy/i3-workspace-names-daemon/blob/5d37153fcc4bde5c8b800be1dd6cb90d9426d8c8/i3_workspace_names_daemon.py#L85

In my interpretation, they are only meant to focus all workspaces and the final focus is then on the originally focused workspace.

I could elliminate this behavior by commenting those two lines out
