### ISSUE TITLE
Adding app-icons.json makes i3-workspace-names-daemon not work.

### ISSUE THREAD

**Issue by ognjenMarinkovic27** [cboddy/i3-workspace-names-daemon#34]
I do not know if this is the right place to report such an issue, but I have found a problem while trying to use this package with custom icons. As soon as I add app-icons.json to ~/.config/i3/config and restart the session the workspace names stop chaning.

**Comment by CastixGitHub** [comment]
weird, are you sure it is valid json? did you check with a json
validator/linter? can you paste it here?
if you lauch it from terminal (-v is a suggested option) do you see
anything, any traceback?
(if you lauch it from terminal, please be sure it's the only one running
(eg see if active with `ps aux | grep names-daemon` copy the PID and kill
it if there)

Il giorno gio 2 lug 2020 alle ore 20:44 Ognjen Marinkovic <
notifications@github.com> ha scritto:

**Comment by ognjenMarinkovic27** [comment]
As for the app-icons.json file, I just copied the example from pypi:
`
{
    "firefox": "firefox",
    "chromium-browser": "chrome",
    "chrome": "chrome",
    "google-chrome": "chrome",
    "x-terminal-emulator": "terminal",
    "thunderbird": "envelope",
    "jetbrains-idea-ce": "edit",
    "nautilus": "folder-open",
    "clementine": "music",
    "vlc": "play",
    "signal": "comment",
    "_no_match": "question",
}
`
Then I logged out, and logged back in, now it's not working.

I can't kill the already running process since its PID keeps changing.

Once I delete app-icons.json, reload i3 and open a new program it starts working again.

**Comment by ognjenMarinkovic27** [comment]
Sorry for the awful formatting, I have not posted much on GitHub. After every comma should be a line break.

**Comment by CastixGitHub** [comment]
there's an extra `,` at the end, after "question" that should be deleted,
sorry for that

Il giorno ven 3 lug 2020 alle ore 11:05 Ognjen Marinkovic <
notifications@github.com> ha scritto:

**Comment by ognjenMarinkovic27** [comment]
It works now, I didn't know a leading comma makes a JSON invalid. Thanks!

**Comment by cboddy** [comment]
Hi @ognjenMarinkovic27, 

Thanks for reporting (and to @CastixGitHub for jumping right in!), this is now fixed in the README. I've also added an example to validate your config-file.
