### ISSUE TITLE
Group Icons

### ISSUE THREAD

**Issue by elightcap** [cboddy/i3-workspace-names-daemon#47]
Right now, if i have three terminals open in one workspace, the workspace is displayed in the bar as `||`

I havent looked at the code, but im wondering if its possible to group the icons, so if they are all the same class or instance or name, to have the workspace just displayed as ``

**Comment by FloydOtsoko** [comment]
you can run the script with `-u` flag already. Use the `-h` to find this info...

**Comment by elightcap** [comment]
thanks, as always RTFM is the answer. sorry about that, really liking this
